# Generated by Django 3.0.7 on 2022-03-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.FileField(max_length=1000000, upload_to=''),
        ),
    ]
