# Generated by Django 3.0.7 on 2022-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20220326_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
