# Generated by Django 3.0.7 on 2022-04-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20220326_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='size',
            field=models.CharField(default=0, max_length=1000000),
        ),
    ]
