# Generated by Django 3.0.7 on 2022-05-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='size',
            new_name='receive_size',
        ),
        migrations.AddField(
            model_name='message',
            name='send_size',
            field=models.CharField(default=0, max_length=1000000),
        ),
    ]
